### ISSUE TITLE
Momentary output

### ISSUE THREAD

**Issue by vontrapp** [flyte/mqtt-io#38] opened 2018-09-02 02:37 UTC
There are cases where you absolutely want an output to be on (off) for a short period. It would be nice to have this contained in the raspi config and not count on a remote client sending the correct temporary command.

**Comment by flyte** [comment] 2018-09-04 10:42
Hi @vontrapp 

I think this is a duplicate of #10 which I've already implemented.

You can use the `set_on_ms` and `set_off_ms` topic suffixes to do this.

Please see this readme section for more info:
https://github.com/flyte/pi-mqtt-gpio#temporary-set

**Comment by flyte** [comment] 2018-09-04 10:43
Oh, hang on - now I see what you mean. You'd like to use the `/set` suffix but have the momentary part configured in the config file. Hmm. I'll have a think about this!

Could you let me know some possible use-cases for this feature?

**Comment by vontrapp** [comment] 2018-09-05 06:24
The use case would be primarily for safety, otherwise the use case is entirely identical to the specific "set_on_ms" topic. Rather, the duration of the momentary switch, which state it switches to and from, are tightly controlled by the configuration on the pi, and not subject to the whims of any published request.

Some devices may be damaged by being held on too long, for example.

I came across this thought using a raspberry for my garage door. Turning the output "on" (low in my case) and leaving it there would override the garage door safety sensors and close it anyway, and would also make it completely unresponsive to physical button presses to try to reverse it. I didn't know about this feature and it could come in handy, but I still don't think I'd want it available as a remote control anyway.

**Comment by vontrapp** [comment] 2018-09-05 06:26
And I don't think this would be a replacement for the "set_on_ms" either, as sometimes you do want that flexibility to do different durations or entirely switch on or off etc.

**Comment by flyte** [comment] 2018-09-05 09:02
Yes, I absolutely agree with you. OK, I'll have a look at how this can be
done.

**Comment by reestr** [comment] 2019-08-06 06:59
I have the same use case as @vontrapp has outlined.  I would like this for safe opening of garage door and to switch my outside lights which are on a relay circuit on/off.

**Comment by iondarie** [comment] 2020-01-01 19:57
any news on this?

**Comment by flyte** [comment] 2020-01-02 12:44
@vontrapp @reestr @iondarie I've implemented this and updated the readme on the `develop` branch. Can you guys test it out before I release it? It's the new `timed_set_ms` digital output config option. For example, if you want to set the output for one second, set `timed_set_ms: 1000`.

**Comment by iondarie** [comment] 2020-01-02 12:47
Sure i will try in a few hours when i get back home.

Thank you

**Comment by iondarie** [comment] 2020-01-02 20:55
TESTED and it works perfect! thank you

**Comment by flyte** [comment] 2020-01-03 14:27
OK great. Thanks for testing it. I'll release a new version in a little while.

**Closed as completed** 2021-01-24 13:20 UTC
Labels: enhancement, awaiting release
