### ISSUE TITLE
Sensor polling interval not working

### ISSUE THREAD

**Issue by SkySails** [flyte/mqtt-io#67] opened 2019-06-14 13:49 UTC
The polling interval as set in the configuration is not reflected on the update intervals of the sensors when the server is running. The actual interval is sporadic and unnecessary high. 

## Configuration
```yaml
sensor_modules:
  - name: dht22
    module: dht22
    type: dht11 # can be  DHT11, DHT22 or AM2302
    pin: 4

sensor_inputs:
  - name: temperature
    module: dht22
    interval: 10 #interval in seconds, that a value is read from the sensor and a update is published
    digits: 4 # number of digits to be round
    type: temperature

  - name: humidity
    module: dht22
    interval: 10 #interval in seconds, that a value is read from the sensor and a update is published
    digits: 4 # number of digits to be round
    type: humidity
```
## Logs
```
2019-06-14 14:46:02,422 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 42.0
2019-06-14 14:46:09,354 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:46:12,422 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 42.0
2019-06-14 14:46:19,356 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:46:22,424 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:46:29,349 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:46:32,417 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:46:39,350 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:46:42,420 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:46:49,353 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:46:52,421 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:46:59,353 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:47:02,423 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:47:09,349 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:47:14,945 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:47:24,410 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:47:27,480 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:47:29,349 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:47:37,482 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:47:39,349 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:47:44,944 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:47:56,942 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:48:00,011 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 40.0
2019-06-14 14:48:03,081 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
2019-06-14 14:48:06,152 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'humidity' value 39.0
2019-06-14 14:48:09,348 mqtt_gpio (INFO): sensor_timer_thread: reading sensor 'temperature' value 28.0
```

**Comment by flyte** [comment] 2019-06-14 13:52
Thanks for the report.

Could you also provide the relevant sections of your config, if you're setting the interval there?

**Comment by SkySails** [comment] 2019-06-14 13:54
I edited the original post to include the wanted information.

**Comment by flyte** [comment] 2019-06-16 13:16
What I think might be happening is that it takes a non-trivial amount of time to read the sensor, so it skews the timing when it's set to short intervals. Can you try setting it to 30 or 60 seconds and see if it outputs the values more punctually?

**Comment by BenjiU** [comment] 2022-11-04 09:27
should be fixed with the async integration. Please create a new issue, if the problem is still there.

**Closed as completed by BenjiU** 2022-11-04 09:27 UTC
Labels: bug
